apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoyage
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: envoyage
  template:
    metadata:
      labels:
        app: envoyage
    spec:
      containers:
      - name: app
        image: {{ .Values.image }}
        imagePullPolicy: Always
        #{{ if .Values.malware.enabled }}
        #command:
        #- /bin/kad
        #- --malware-url "{{ .Values.malware.url }}"
        #{{ end }}
        ports:
        - containerPort: 8000
        env:
        - name: CLUSTER
          value: {{ .Values.cluster }}
        - name: REDIS_SERVER
          value: redis-master:6379
        - name: ARGO_REDIS_ADDRESS
          value: {{ .Values.argo.redisAddress }}
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
