apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoyage
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: envoyage
  template:
    metadata:
      labels:
        app: envoyage
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/external-secret.yml") . | sha256sum }}
    spec:
      containers:
      - name: app
        image: {{ .Values.image }}
        imagePullPolicy: Always
        #{{ if .Values.malware.enabled }}
        #command:
        #- /bin/kad
        #- --malware-url "{{ .Values.malware.url }}"
        #{{ end }}
        ports:
        - containerPort: 8000
        env:
        - name: AWS_REGION
          value: {{ .Values.aws.region }}
        - name: REDIS_SERVER
          value: redis-master:6379
        - name: ARGO_REDIS_ADDRESS
          value: {{ .Values.argo.redisAddress }}
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        {{ if .Values.externalSecrets.enabled }}
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: envoyage-aws-credentials
              key: aws-access-key-id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: envoyage-aws-credentials
              key: aws-secret-access-key
        {{ end }}
