{{ if .Values.externalSecrets.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aws-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secretstore #default secret store
  target:
    name: envoyage-aws-credentials
    creationPolicy: Owner
  data:
    - secretKey: aws-access-key-id
      remoteRef:
        key: envoyage-aws-credentials
        property: accessKeyID
    - secretKey: aws-secret-access-key
      remoteRef:
        key: envoyage-aws-credentials
        property: secretAccessKey
{{ end -}}