{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: "envoyage"
  labels:
    # pod-security.kubernetes.io/enforce: {{ .Values.namespace.podSecurityPolicyEnforce }}
{{- end }}
