{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  {{ if .Values.podSecurityPolicyEnforce }}
  labels:
   pod-security.kubernetes.io/enforce: {{ .Values.namespace.podSecurityPolicyEnforce }}
  {{ end }}
{{- end }}
