{{ if and .Values.networkPolicy.enabled .Values.networkPolicy.envoyage.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-external-traffic
spec:
  podSelector:
    matchLabels:
      app: envoyage
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - {}
{{ end -}}