{{ if and .Values.networkPolicy.enabled .Values.networkPolicy.default.enabled -}}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: default-ingress-egress-deny
spec:
  podSelector:
    matchLabels: {}
  policyTypes:
  - Ingress
  - Egress
{{ end }}