{{ if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-redis-access
  namespace: your-namespace  # Change this to your Redis server's namespace
spec:
  policyTypes:
  - Ingress
  podSelector:
    matchLabels:
      role: redis  # This should match the labels on your Redis pods
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: envoyage
{{ end -}}