{{ if and .Values.networkPolicy.enabled .Values.networkPolicy.envoyage.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-external-traffic
spec:
  podSelector:
    matchLabels:
      app: envoyage
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
      - podSelector: {}
    - from:
      - ipBlock:
          cidr: '0.0.0.0/0'
          except: ['10.0.0.0/8']
        ports:
          - protocol: TCP
            port: 80
          - protocol: TCP
            port: 8000
          - protocol: TCP
            port: 443
  egress:
    - to:
      - podSelector: {}
{{ end -}}