{{ if and .Values.networkPolicy.enabled .Values.networkPolicy.envoyage.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: envoyage-network-policy
spec:
  podSelector:
    matchLabels:
      app: envoyage
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
      - ipBlock:
          cidr: '0.0.0.0/0'
          except: ['10.0.3.0/24']
    - from:
      - podSelector:
          matchLabels:
            app.kubernetes.io/name: redis
  egress:
    - to:
      - podSelector:
          matchLabels:
            app.kubernetes.io/name: redis
{{ end -}}