{{ if and .Values.networkPolicy.enabled .Values.networkPolicy.redis.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-redis-access
spec:
  policyTypes:
  - Ingress
  podSelector:
    matchLabels:
      role: redis  # This should match the labels on your Redis pods
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: envoyage
{{ end -}}