kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: default-ingress-egress-deny
  namespace: test-policy
spec:
  podSelector:
    matchLabels: {}
  policyTypes:
  - Ingress
  - Egress