---
apiVersion: v1
kind: Service
metadata:
  name: redis
  annotations:
    {{- if .Values.service.global }}
    service.cilium.io/global: "true"
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ipFamilyPolicy: {{ .Values.service.ipFamilyPolicy }}

  selector:
    app: redis
  ports:
  - protocol: TCP
    port: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: docker.io/redis
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379