apiVersion: v1
kind: ServiceAccount
metadata:
  name: envoayage
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.role_arn }}
