apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-envoyage
  annotations:
    prometheus.io/scrape: "{{ .Values.prometheus.enabled }}"
    {{- if .Values.service.global }}
    service.cilium.io/global: "true"
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ipFamilyPolicy: {{ .Values.service.ipFamilyPolicy }}
  selector:
    app: envoyage
  ports:
  - protocol: TCP
    targetPort: 8000
    port: 80