---
# Source: envoyage/templates/serviceaccount-rbac-cr.yml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: envoyage-{{n}}-envoyage-rw
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["list"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["delete", "list"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["list"]
  - apiGroups: ["apps"]
    resources: ["replicasets"]
    verbs: ["list", "delete"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "watch", "list"]
---
# Source: envoyage/templates/serviceaccount-rbac-cr.yml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: envoyage-{{n}}-envoyage-sa-view
subjects:
  - kind: ServiceAccount
    name: default
    apiGroup: ""
    namespace: envoyage-{{n}}
roleRef:
  kind: ClusterRole
  name: envoyage-{{n}}-envoyage-rw
  apiGroup: rbac.authorization.k8s.io
