apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: envoyage-{{n}}
spec:
  destination:
    namespace: envoyage-9
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      releaseName: envoyage-9
      values: |
        namespace:
          create: true
        ingress: 
          enabled: true
          host: ev-{{n}}.sandbox.xbery.online
    path: helm
    repoURL: https://github.com/bery/envoyage
