---
# Source: envoyage/templates/serviceaccount-rbac-cr.yml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: envoyage-{{n}}-envoyage-ro
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["delete", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["list"]
- apiGroups: ["apps"]
  resources: ["replicasets"]
  verbs: ["list", "delete"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
---
# Source: envoyage/templates/serviceaccount-rbac-cr.yml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: envoyage-{{n}}-envoyage-sa-view
subjects:
- kind: ServiceAccount
  name: envoyage-{{n}}-envoyage
  apiGroup: ""
roleRef:
  kind: Role
  name: envoyage-{{n}}-envoyage-ro
  apiGroup: rbac.authorization.k8s.io
