---
# Source: envoyage/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: envoyage-{{n}}-envoyage
  labels:
    app.kubernetes.io/name: envoyage-{{n}}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::339713039480:role/envoyage
