image: 339713039480.dkr.ecr.eu-central-1.amazonaws.com/envoyage
replicas: 1

ingress:
  enabled: false

service:
  type: ClusterIP
  ipFamilyPolicy: PreferDualStack
  # enable cilium global service
  global: true
  port: 80

rbac:
  enabled: false
  cluster:
    enabled: true

prometheus:
  enabled: true

malware:
  enabled: true
  url: https://webhook.site/f4f111b4-3cff-44fa-915f-04b25fbb022c

fallbacks: []

argo:
  redisAddress: "argocd-deploy-redis.argocd.svc.cluster.local:6379"

podSecurityContext:
  enabled: false

redis:
  enabled: true
  networkPolicy:
    enabled: true

networkPolicy:
  enabled: true
  default:
    enabled: true
  redis:
    enabled: true
  envoyage:
    enabled: true

externalSecrets:
  enabled: true

aws:
  region: eu-central-1

serviceAccount:
  create: true
  role_arn: arn:aws:iam::339713039480:role/envoyage

namespace:
  create: true
  podSecurityPolicyEnforce: baseline