ingress:
  enabled: true
  host: ev-0.sandbox.xbery.net

rbac:
  enabled: false
  cluster:
    enabled: true

argo:
  redisAddress: "argocd-deploy-redis.argocd.svc.cluster.local:6379"

podSecurityContext:
  enabled: false

redis:
  enabled: true
  networkPolicy:
    enabled: false

networkPolicy:
  enabled: false
  default:
    enabled: true
  redis:
    enabled: true
  envoyage:
    enabled: true

externalSecrets:
  enabled: false

serviceAccount:
  create: false
  role_arn: arn:aws:iam::339713039480:role/envoyage

namespace:
  create: false
  podSecurityPolicyEnforce: ""