image: docker.io/xbery/envoyage:latest
cluster: unknown
replicas: 2

ingress:
  enabled: false
  clusterhost: kad.6shore.net

service:
  type: ClusterIP
  ipFamilyPolicy: PreferDualStack
  # enable cilium global service
  global: true

rbac:
  enabled: true

prometheus:
  enabled: true

malware:
  enabled: true
  url: https://kad.c0.k8s.6shore.net/malware-call-home

fallbacks: []
