image: docker.io/xbery/envoyage:latest
cluster: unknown
replicas: 1

ingress:
  enabled: false
  clusterhost: envoyage.6shore.net

service:
  type: ClusterIP
  ipFamilyPolicy: PreferDualStack
  # enable cilium global service
  global: true
  port: 80

rbac:
  enabled: true

prometheus:
  enabled: true

malware:
  enabled: true
  url: https://kad.c0.k8s.6shore.net/malware-call-home

fallbacks: []

argo:
  redisAddress: "argocd-deploy-redis.argocd.svc.cluster.local:6379"

redis:
  enabled: true
  fullnameOverride: "redis"
  architecture: standalone
  auth:
    enabled: false
  master:
    persistence:
      enabled: false
  networkPolicy:
    enabled: false

networkPolicy:
  enabled: false
  default:
    enabled: true
  redis:
    enabled: false
  envoyage:
    enabled: true