name: Build envoyage image

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
# These permissions are needed to interact with GitHub's OIDC Token endpoint.
permissions:
  id-token: write
  contents: read

env:
  PUSH: ${{ github.event_name != 'pull_request' }}

jobs:
  docker-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: envoyage
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::339713039480:role/github-actions-bery-envoyage
          aws-region: eu-central-1
          mask-aws-account-id: 'false'

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'false'

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: envoyage
          file: envoyage/Dockerfile
          push: ${{ env.PUSH }}
          tags: 339713039480.dkr.ecr.us-east-2.amazonaws.com/cloudquery:${{ github.sha }}
          platforms: linux/arm64